# GitHub links for PyPI packages
github_links = [
    {"dependency": "django-elasticsearch-dsl", "github_url": "https://github.com/sabricot/django-elasticsearch-dsl"},
    {"dependency": "cfn-lint", "github_url": "https://github.com/aws-cloudformation/cfn-python-lint"},
    {"dependency": "edx-search", "github_url": "https://github.com/openedx/edx-search"},
    {"dependency": "pbr", "github_url": "No Github Link"},
    {"dependency": "pypng", "github_url": "No Github Link"},
    {"dependency": "loremipsum", "github_url": "No Github Link"},
    {"dependency": "psutil", "github_url": "https://github.com/giampaolo/psutil"},
    {"dependency": "docopt", "github_url": "No Github Link"},
    {"dependency": "redis", "github_url": "https://github.com/redis/redis-py"},
    {"dependency": "backports.entry-points-selectable", "github_url": "https://github.com/jaraco/backports.entry_points_selectable"},
    {"dependency": "python-cjson", "github_url": "https://github.com/AGProjects/python-cjson"},
    {"dependency": "gspread", "github_url": "https://github.com/burnash/gspread"},
    {"dependency": "python-swiftclient", "github_url": "No Github Link"},
    {"dependency": "appium-python-client", "github_url": "No Github Link"},
    {"dependency": "rq", "github_url": "https://github.com/nvie/rq/"},
    {"dependency": "google-cloud-translate", "github_url": "https://github.com/googleapis/python-translate"},
    {"dependency": "django-environ", "github_url": "https://github.com/joke2k/django-environ"},
    {"dependency": "django-cache-memoize", "github_url": "https://github.com/peterbe/django-cache-memoize"},
    {"dependency": "autocommand", "github_url": "https://github.com/Lucretiel/autocommand"},
    {"dependency": "django-object-actions", "github_url": "https://github.com/crccheck/django-object-actions"},
    {"dependency": "edx-django-sites-extensions", "github_url": "https://github.com/openedx/edx-django-sites-extensions"},
    {"dependency": "libsass", "github_url": "No Github Link"},
    {"dependency": "cached-property", "github_url": "https://github.com/pydanny/cached-property"},
    {"dependency": "h11", "github_url": "https://github.com/python-hyper/h11"},
    {"dependency": "pytest-rerunfailures", "github_url": "https://github.com/pytest-dev/pytest-rerunfailures"},
    {"dependency": "requests-aws4auth", "github_url": "https://github.com/tedder/requests-aws4auth"},
    {"dependency": "click-log", "github_url": "https://github.com/click-contrib/click-log"},
    {"dependency": "minimal-snowplow-tracker", "github_url": "No Github Link"},
    {"dependency": "sphinxcontrib-devhelp", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-devhelp"},
    {"dependency": "zope-interface", "github_url": "https://github.com/zopefoundation/zope.interface"},
    {"dependency": "event-tracking", "github_url": "https://github.com/openedx/event-tracking"},
    {"dependency": "gitpython", "github_url": "https://github.com/gitpython-developers/GitPython"},
    {"dependency": "sailthru-client", "github_url": "https://github.com/sailthru/sailthru-python-client"},
    {"dependency": "django-dynamic-filenames", "github_url": "https://github.com/codingjoe/django-dynamic-filenames"},
    {"dependency": "ordereddict", "github_url": "No Project Links Tab"},
    {"dependency": "elasticsearch-dsl", "github_url": "https://github.com/elasticsearch/elasticsearch-dsl-py"},
    {"dependency": "asttokens", "github_url": "https://github.com/gristlabs/asttokens"},
    {"dependency": "xmlformatter", "github_url": "No Github Link"},
    {"dependency": "logutils", "github_url": "No Github Link"},
    {"dependency": "taxonomy-connector", "github_url": "https://github.com/openedx/taxonomy-connector"},
    {"dependency": "ansible-core", "github_url": "https://github.com/ansible/ansible"},
    {"dependency": "pluggy", "github_url": "https://github.com/pytest-dev/pluggy"},
    {"dependency": "pysrt", "github_url": "https://github.com/byroot/pysrt"},
    {"dependency": "django-method-override", "github_url": "No Github Link"},
    {"dependency": "python3-openid", "github_url": "No Github Link"},
    {"dependency": "python-dateutil", "github_url": "https://github.com/dateutil/dateutil"},
    {"dependency": "waitress", "github_url": "https://github.com/Pylons/waitress"},
    {"dependency": "logilab-common", "github_url": "No Github Link"},
    {"dependency": "jsonfield2", "github_url": "https://github.com/rpkilby/jsonfield2/"},
    {"dependency": "enum34", "github_url": "No Github Link"},
    {"dependency": "cherrypy", "github_url": "https://github.com/cherrypy/cherrypy"},
    {"dependency": "sphinx-rtd-theme", "github_url": "https://github.com/readthedocs/sphinx_rtd_theme"},
    {"dependency": "xblock-drag-and-drop-v2", "github_url": "https://github.com/openedx/xblock-drag-and-drop-v2"},
    {"dependency": "edx-token-utils", "github_url": "https://github.com/edx/token-utils"},
    {"dependency": "ptvsd", "github_url": "No Github Link"},
    {"dependency": "google-cloud-secret-manager", "github_url": "https://github.com/googleapis/google-cloud-python"},
    {"dependency": "pyjwt", "github_url": "https://github.com/jpadilla/pyjwt"},
    {"dependency": "gunicorn", "github_url": "https://github.com/benoitc/gunicorn"},
    {"dependency": "dill", "github_url": "https://github.com/uqfoundation/dill"},
    {"dependency": "pyrsistent", "github_url": "https://github.com/tobgu/pyrsistent/"},
    {"dependency": "fasteners", "github_url": "https://github.com/harlowja/fasteners"},
    {"dependency": "pypi", "github_url": "No Github Link"},
    {"dependency": "markupsafe", "github_url": "https://github.com/pallets/markupsafe/"},
    {"dependency": "croniter", "github_url": "No Github Link"},
    {"dependency": "boltons", "github_url": "https://github.com/mahmoud/boltons"},
    {"dependency": "openedx-ledger", "github_url": "https://github.com/openedx/openedx-ledger"},
    {"dependency": "pybase64", "github_url": "https://github.com/mayeut/pybase64"},
    {"dependency": "parsimonious", "github_url": "https://github.com/erikrose/parsimonious"},
    {"dependency": "jsondiff", "github_url": "https://github.com/ZoomerAnalytics/jsondiff"},
    {"dependency": "apache-libcloud", "github_url": "https://github.com/apache/libcloud"},
    {"dependency": "django-soapbox", "github_url": "https://github.com/ubernostrum/django-soapbox"},
    {"dependency": "ply", "github_url": "No Github Link"},
    {"dependency": "jaraco-classes", "github_url": "https://github.com/jaraco/jaraco.classes"},
    {"dependency": "pylatexenc", "github_url": "https://github.com/phfaist/pylatexenc"},
    {"dependency": "six", "github_url": "https://github.com/benjaminp/six"},
    {"dependency": "didkit", "github_url": "https://github.com/spruceid/didkit/"},
    {"dependency": "chardet", "github_url": "https://github.com/chardet/chardet"},
    {"dependency": "sphinxcontrib-httpdomain", "github_url": "https://github.com/sphinx-contrib/httpdomain"},
    {"dependency": "livereload", "github_url": "https://github.com/lepture/python-livereload"},
    {"dependency": "nh3", "github_url": "https://github.com/messense/nh3"},
    {"dependency": "werkzeug", "github_url": "https://github.com/pallets/werkzeug/"},
    {"dependency": "deepmerge", "github_url": "No Github Link"},
    {"dependency": "openedx-blockstore", "github_url": "https://github.com/openedx/blockstore"},
    {"dependency": "edx-ace", "github_url": "https://github.com/openedx/edx-ace"},
    {"dependency": "django-phonenumber-field", "github_url": "https://github.com/stefanfoulis/django-phonenumber-field"},
    {"dependency": "sphinxcontrib-websupport", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-websupport"},
    {"dependency": "django-durationwidget", "github_url": "https://github.com/devangpadhiyar/django-durationwidget"},
    {"dependency": "django-stubs-ext", "github_url": "https://github.com/typeddjango/django-stubs"},
    {"dependency": "ruamel-yaml-convert", "github_url": "No Github Link"},
    {"dependency": "ua-parser", "github_url": "https://github.com/ua-parser/uap-python"},
    {"dependency": "pathtools", "github_url": "No Github Link"},
    {"dependency": "tblib", "github_url": "https://github.com/ionelmc/python-tblib"},
    {"dependency": "click-didyoumean", "github_url": "No Project Links Tab"},
    {"dependency": "markdown", "github_url": "https://github.com/Python-Markdown/markdown"},
    {"dependency": "sphinxcontrib-images", "github_url": "https://github.com/sphinx-contrib/images"},
    {"dependency": "faker", "github_url": "https://github.com/joke2k/faker"},
    {"dependency": "cron-descriptor", "github_url": "https://github.com/Salamek/cron-descriptor"},
    {"dependency": "django-splash", "github_url": "https://github.com/openedx/django-splash"},
    {"dependency": "django-js-asset", "github_url": "https://github.com/matthiask/django-js-asset/"},
    {"dependency": "pydata-sphinx-theme", "github_url": "https://github.com/pydata/pydata-sphinx-theme"},
    {"dependency": "altgraph", "github_url": "https://github.com/ronaldoussoren/altgraph"},
    {"dependency": "django-filter", "github_url": "https://github.com/carltongibson/django-filter"},
    {"dependency": "grimp", "github_url": "https://github.com/seddonym/grimp/"},
    {"dependency": "semgrep", "github_url": "https://github.com/returntocorp/semgrep"},
    {"dependency": "django-braces", "github_url": "https://github.com/brack3t/django-braces/"},
    {"dependency": "pylint-django", "github_url": "https://github.com/PyCQA/pylint-django"},
    {"dependency": "nose", "github_url": "No Github Link"},
    {"dependency": "hypothesis", "github_url": "No Github Link"},
    {"dependency": "pyflakes", "github_url": "https://github.com/PyCQA/pyflakes"},
    {"dependency": "python-jose", "github_url": "https://github.com/mpdavis/python-jose/"},
    {"dependency": "pytest-responses", "github_url": "https://github.com/getsentry/pytest-responses"},
    {"dependency": "filetype", "github_url": "https://github.com/h2non/filetype.py"},
    {"dependency": "freezegun", "github_url": "https://github.com/spulec/freezegun"},
    {"dependency": "shapely", "github_url": "https://github.com/shapely/shapely"},
    {"dependency": "jsonfield", "github_url": "https://github.com/rpkilby/jsonfield/"},
    {"dependency": "celery", "github_url": "https://github.com/celery/celery"},
    {"dependency": "jsonpatch", "github_url": "https://github.com/stefankoegl/python-json-patch"},
    {"dependency": "django-lang-pref-middleware", "github_url": "https://github.com/openedx/django-lang-pref-middleware"},
    {"dependency": "rfc3339-validator", "github_url": "https://github.com/naimetti/rfc3339-validator"},
    {"dependency": "pillow", "github_url": "https://github.com/python-pillow/Pillow"},
    {"dependency": "x509", "github_url": "https://github.com/cniemira/py3x509"},
    {"dependency": "nodeenv", "github_url": "https://github.com/ekalinin/nodeenv"},
    {"dependency": "pytest-repeat", "github_url": "https://github.com/pytest-dev/pytest-repeat"},
    {"dependency": "jsx-lexer", "github_url": "https://github.com/fcurella/jsx-lexer"},
    {"dependency": "edx-ccx-keys", "github_url": "https://github.com/edx/ccx-keys"},
    {"dependency": "jsonlines", "github_url": "https://github.com/wbolster/jsonlines"},
    {"dependency": "pycurl", "github_url": "No Github Link"},
    {"dependency": "kappa", "github_url": "https://github.com/garnaat/kappa"},
    {"dependency": "pytest-timeout", "github_url": "https://github.com/pytest-dev/pytest-timeout"},
    {"dependency": "cheroot", "github_url": "https://github.com/cherrypy/cheroot"},
    {"dependency": "django-compressor", "github_url": "https://github.com/django-compressor/django-compressor"},
    {"dependency": "jeepney", "github_url": "No Github Link"},
    {"dependency": "snowflake-connector-python", "github_url": "https://github.com/snowflakedb/snowflake-connector-python"},
    {"dependency": "unidiff", "github_url": "No Github Link"},
    {"dependency": "junit-xml", "github_url": "https://github.com/kyrus/python-junit-xml"},
    {"dependency": "pytest-asyncio", "github_url": "https://github.com/pytest-dev/pytest-asyncio"},
    {"dependency": "decorator", "github_url": "https://github.com/micheles/decorator"},
    {"dependency": "pycodestyle", "github_url": "No Github Link"},
    {"dependency": "mako", "github_url": "https://github.com/sqlalchemy/mako"},
    {"dependency": "docutils", "github_url": "No Github Link"},
    {"dependency": "django-storages", "github_url": "https://github.com/jschneier/django-storages"},
    {"dependency": "nose-ignore-docstring", "github_url": "https://github.com/schlamar/nose-ignore-docstring"},
    {"dependency": "cssselect2", "github_url": "https://github.com/Kozea/cssselect2/"},
    {"dependency": "pytest-cov", "github_url": "https://github.com/pytest-dev/pytest-cov"},
    {"dependency": "django-timezone-field", "github_url": "https://github.com/mfogel/django-timezone-field/"},
    {"dependency": "python-toolbox", "github_url": "No Project Links Tab"},
    {"dependency": "flake8", "github_url": "https://github.com/pycqa/flake8"},
    {"dependency": "partd", "github_url": "No Github Link"},
    {"dependency": "attrs", "github_url": "https://github.com/python-attrs/attrs"},
    {"dependency": "astroid", "github_url": "https://github.com/pylint-dev/astroid"},
    {"dependency": "django-elasticsearch-dsl-drf", "github_url": "https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/"},
    {"dependency": "django-statici18n", "github_url": "https://github.com/zyegfryed/django-statici18n"},
    {"dependency": "xss-utils", "github_url": "https://github.com/openedx/xss-utils"},
    {"dependency": "zict", "github_url": "No Github Link"},
    {"dependency": "drf-jwt", "github_url": "https://github.com/Styria-Digital/django-rest-framework-jwt"},
    {"dependency": "py-partiql-parser", "github_url": "https://github.com/getmoto/py-partiql-parser"},
    {"dependency": "pytz", "github_url": "No Github Link"},
    {"dependency": "path-py", "github_url": "https://github.com/jaraco/path"},
    {"dependency": "edx-celeryutils", "github_url": "https://github.com/openedx/edx-celeryutils"},
    {"dependency": "django-haystack", "github_url": "https://github.com/django-haystack/django-haystack"},
    {"dependency": "django-simple-history", "github_url": "https://github.com/jazzband/django-simple-history"},
    {"dependency": "trio", "github_url": "https://github.com/python-trio/trio"},
    {"dependency": "diff-cover", "github_url": "https://github.com/Bachmann1234/diff-cover"},
    {"dependency": "unicodecsv", "github_url": "https://github.com/jdunck/python-unicodecsv"},
    {"dependency": "fixtures", "github_url": "https://github.com/testing-cabal/fixtures"},
    {"dependency": "openedx-calc", "github_url": "https://github.com/edx/openedx-calc"},
    {"dependency": "sphinx-panels", "github_url": "https://github.com/executablebooks/sphinx-panels"},
    {"dependency": "alabaster", "github_url": "https://github.com/bitprophet/alabaster"},
    {"dependency": "linecache2", "github_url": "https://github.com/testing-cabal/linecache2"},
    {"dependency": "django-countries", "github_url": "https://github.com/SmileyChris/django-countries/"},
    {"dependency": "boto", "github_url": "https://github.com/boto/boto/"},
    {"dependency": "wheel", "github_url": "No Github Link"},
    {"dependency": "sqlparse", "github_url": "https://github.com/andialbrecht/sqlparse"},
    {"dependency": "django-contrib-comments", "github_url": "https://github.com/django/django-contrib-comments"},
    {"dependency": "chem", "github_url": "https://github.com/edx/openedx-chem"},
    {"dependency": "click", "github_url": "https://github.com/pallets/click/"},
    {"dependency": "sphinx-autobuild", "github_url": "https://github.com/executablebooks/sphinx-autobuild"},
    {"dependency": "edx-django-release-util", "github_url": "No Github Link"},
    {"dependency": "secretstorage", "github_url": "https://github.com/mitya57/secretstorage"},
    {"dependency": "xlsxwriter", "github_url": "https://github.com/jmcnamara/XlsxWriter"},
    {"dependency": "google-auth", "github_url": "https://github.com/googleapis/google-auth-library-python"},
    {"dependency": "urllib3", "github_url": "https://github.com/urllib3/urllib3"},
    {"dependency": "mock", "github_url": "https://github.com/testing-cabal/mock"},
    {"dependency": "fsspec", "github_url": "https://github.com/fsspec/filesystem_spec"},
    {"dependency": "django-fernet-fields-v2", "github_url": "https://github.com/MichelML/django-fernet-fields"},
    {"dependency": "sphinxcontrib-yt", "github_url": "https://github.com/divi255/sphinxcontrib.youtube"},
    {"dependency": "google-cloud-aiplatform", "github_url": "https://github.com/googleapis/python-aiplatform"},
    {"dependency": "openedx-learning", "github_url": "https://github.com/openedx/openedx-learning"},
    {"dependency": "aws-xray-sdk", "github_url": "https://github.com/aws/aws-xray-sdk-python"},
    {"dependency": "tqdm", "github_url": "https://github.com/tqdm/tqdm"},
    {"dependency": "edx-codejail", "github_url": "https://github.com/openedx/codejail"},
    {"dependency": "uritemplate", "github_url": "No Github Link"},
    {"dependency": "azure-storage-blob", "github_url": "No Github Link"},
    {"dependency": "openapi-codec", "github_url": "No Github Link"},
    {"dependency": "l18n", "github_url": "https://github.com/tkhyn/l18n"},
    {"dependency": "pymongo", "github_url": "No Github Link"},
    {"dependency": "jaraco-text", "github_url": "https://github.com/jaraco/jaraco.text"},
    {"dependency": "jasmine-core", "github_url": "No Github Link"},
    {"dependency": "pylint-celery", "github_url": "https://github.com/landscapeio/pylint-celery"},
    {"dependency": "jasmine", "github_url": "No Github Link"},
    {"dependency": "virtualenv", "github_url": "https://github.com/pypa/virtualenv"},
    {"dependency": "click-repl", "github_url": "https://github.com/untitaker/click-repl"},
    {"dependency": "analytics-python", "github_url": "https://github.com/segmentio/analytics-python"},
    {"dependency": "edx-ecommerce-worker", "github_url": "https://github.com/openedx/ecommerce-worker"},
    {"dependency": "edx-tincan-py35", "github_url": "No Github Link"},
    {"dependency": "edx-submissions", "github_url": "No Github Link"},
    {"dependency": "glom", "github_url": "https://github.com/mahmoud/glom"},
    {"dependency": "dask", "github_url": "https://github.com/dask/dask/"},
    {"dependency": "django-rest-framework", "github_url": "No Github Link"},
    {"dependency": "pprintpp", "github_url": "https://github.com/wolever/pprintpp"},
    {"dependency": "volatile", "github_url": "https://github.com/mbr/volatile"},
    {"dependency": "starlette", "github_url": "https://github.com/sponsors/encode"},
    {"dependency": "yamllint", "github_url": "https://github.com/adrienverge/yamllint"},
    {"dependency": "maxminddb", "github_url": "https://github.com/maxmind/MaxMind-DB-Reader-python"},
    {"dependency": "django-storage-swift", "github_url": "https://github.com/dennisv/django-storage-swift"},
    {"dependency": "rsa", "github_url": "https://github.com/sybrenstuvel/python-rsa"},
    {"dependency": "djangorestframework-xml", "github_url": "https://github.com/jpadilla/django-rest-framework-xml"},
    {"dependency": "httpretty", "github_url": "https://github.com/gabrielfalcao/httpretty"},
    {"dependency": "schema", "github_url": "https://github.com/keleshev/schema"},
    {"dependency": "bump2version", "github_url": "https://github.com/c4urself/bump2version"},
    {"dependency": "olxcleaner", "github_url": "https://github.com/openedx/olxcleaner"},
    {"dependency": "botocore", "github_url": "https://github.com/boto/botocore"},
    {"dependency": "asn1crypto", "github_url": "https://github.com/wbond/asn1crypto"},
    {"dependency": "fissix", "github_url": "https://github.com/jreese/fissix"},
    {"dependency": "dockerpty", "github_url": "https://github.com/d11wtq/dockerpty"},
    {"dependency": "pylint-plugin-utils", "github_url": "https://github.com/PyCQA/pylint-plugin-utils"},
    {"dependency": "coreschema", "github_url": "https://github.com/core-api/python-coreschema"},
    {"dependency": "doc8", "github_url": "https://github.com/pycqa/doc8"},
    {"dependency": "s3transfer", "github_url": "https://github.com/boto/s3transfer"},
    {"dependency": "heapdict", "github_url": "No Github Link"},
    {"dependency": "django-bootstrap3", "github_url": "https://github.com/zostera/django-bootstrap3"},
    {"dependency": "filechunkio", "github_url": "No Github Link"},
    {"dependency": "google-cloud-resource-manager", "github_url": "https://github.com/googleapis/google-cloud-python"},
    {"dependency": "contextlib2", "github_url": "No Github Link"},
    {"dependency": "sphinx-book-theme", "github_url": "https://github.com/executablebooks/sphinx-book-theme"},
    {"dependency": "oscrypto", "github_url": "https://github.com/wbond/oscrypto"},
    {"dependency": "coverage", "github_url": "https://github.com/nedbat/coveragepy"},
    {"dependency": "httpcore", "github_url": "https://github.com/encode/httpcore"},
    {"dependency": "mailsnake", "github_url": "https://github.com/michaelhelmick/python-mailsnake"},
    {"dependency": "draftjs-exporter", "github_url": "https://github.com/springload/draftjs_exporter"},
    {"dependency": "avro", "github_url": "No Github Link"},
    {"dependency": "imagesize", "github_url": "https://github.com/shibukawa/imagesize_py"},
    {"dependency": "cycler", "github_url": "https://github.com/matplotlib/cycler"},
    {"dependency": "cybersource-rest-client-python", "github_url": "https://github.com/CyberSource/cybersource-rest-client-python"},
    {"dependency": "crispy-bootstrap3", "github_url": "https://github.com/django-crispy-forms/crispy-bootstrap3"},
    {"dependency": "validators", "github_url": "https://github.com/python-validators/validators"},
    {"dependency": "logger", "github_url": "No Project Links Tab"},
    {"dependency": "locket", "github_url": "No Github Link"},
    {"dependency": "requests-toolbelt", "github_url": "https://github.com/requests/toolbelt"},
    {"dependency": "django-model-utils", "github_url": "https://github.com/jazzband/django-model-utils"},
    {"dependency": "lti-consumer-xblock", "github_url": "https://github.com/openedx/xblock-lti-consumer"},
    {"dependency": "python-daemon", "github_url": "No Github Link"},
    {"dependency": "willow", "github_url": "https://github.com/wagtail/Willow"},
    {"dependency": "backoff", "github_url": "https://github.com/litl/backoff"},
    {"dependency": "pydantic", "github_url": "https://github.com/pydantic/pydantic"},
    {"dependency": "jaraco-collections", "github_url": "https://github.com/jaraco/jaraco.collections"},
    {"dependency": "vulture", "github_url": "https://github.com/jendrikseipp/vulture"},
    {"dependency": "django-threadlocals", "github_url": "https://github.com/nebstrebor/django-threadlocals"},
    {"dependency": "staff-graded-xblock", "github_url": "https://github.com/openedx/staff_graded-xblock"},
    {"dependency": "django-crum", "github_url": "https://github.com/ninemoreminutes/django-crum/"},
    {"dependency": "protobuf", "github_url": "No Github Link"},
    {"dependency": "edx-drf-extensions", "github_url": "https://github.com/openedx/edx-drf-extensions"},
    {"dependency": "requests-oauthlib", "github_url": "https://github.com/requests/requests-oauthlib"},
    {"dependency": "pylti1p3", "github_url": "https://github.com/dmitry-viskov/pylti1.3"},
    {"dependency": "python-subunit", "github_url": "https://github.com/testing-cabal/subunit/"},
    {"dependency": "aniso8601", "github_url": "No Github Link"},
    {"dependency": "lz4", "github_url": "https://github.com/python-lz4/python-lz4"},
    {"dependency": "django-multiselectfield", "github_url": "https://github.com/goinnn/django-multiselectfield"},
    {"dependency": "openpyxl", "github_url": "No Github Link"},
    {"dependency": "django-config-models", "github_url": "https://github.com/openedx/django-config-models"},
    {"dependency": "edx-sga", "github_url": "https://github.com/mitodl/edx-sga"},
    {"dependency": "django-cors-headers", "github_url": "https://github.com/adamchainz/django-cors-headers"},
    {"dependency": "openedx-django-pyfs", "github_url": "https://github.com/openedx/django-pyfs"},
    {"dependency": "portend", "github_url": "https://github.com/jaraco/portend"},
    {"dependency": "tox-battery", "github_url": "https://github.com/signalpillar/tox-battery"},
    {"dependency": "getsmarter-api-clients", "github_url": "https://github.com/edx/getsmarter-api-clients"},
    {"dependency": "httmock", "github_url": "https://github.com/patrys/httmock"},
    {"dependency": "python-slugify", "github_url": "https://github.com/un33k/python-slugify"},
    {"dependency": "ruamel-yaml-cmd", "github_url": "No Github Link"},
    {"dependency": "kombu", "github_url": "https://github.com/celery/kombu"},
    {"dependency": "requests-file", "github_url": "No Github Link"},
    {"dependency": "vine", "github_url": "https://github.com/celery/vine"},
    {"dependency": "pytest-pep8", "github_url": "No Github Link"},
    {"dependency": "mashumaro", "github_url": "https://github.com/Fatal1ty/mashumaro"},
    {"dependency": "django-modelcluster", "github_url": "https://github.com/wagtail/django-modelcluster"},
    {"dependency": "xblock", "github_url": "https://github.com/openedx/XBlock"},
    {"dependency": "configobj", "github_url": "https://github.com/DiffSK/configobj"},
    {"dependency": "onelogin-aws-assume-role", "github_url": "https://github.com/onelogin/onelogin-python-aws-assume-role"},
    {"dependency": "tenacity", "github_url": "https://github.com/jd/tenacity"},
    {"dependency": "app-store-notifications-v2-validator", "github_url": "https://github.com/rickwierenga/app-store-notifications-v2-validator"},
    {"dependency": "django-appconf", "github_url": "https://github.com/django-compressor/django-appconf"},
    {"dependency": "oauthlib", "github_url": "https://github.com/oauthlib/oauthlib"},
    {"dependency": "appdirs", "github_url": "No Github Link"},
    {"dependency": "types-python-dateutil", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "factory-boy", "github_url": "https://github.com/FactoryBoy/factory_boy"},
    {"dependency": "edx-enterprise", "github_url": "https://github.com/openedx/edx-enterprise"},
    {"dependency": "cairosvg", "github_url": "https://github.com/Kozea/CairoSVG/"},
    {"dependency": "html2text", "github_url": "https://github.com/Alir3z4/html2text/"},
    {"dependency": "chevron", "github_url": "https://github.com/noahmorrison/chevron"},
    {"dependency": "contentful", "github_url": "https://github.com/contentful/contentful.py"},
    {"dependency": "django-user-tasks", "github_url": "https://github.com/openedx/django-user-tasks"},
    {"dependency": "django-classy-tags", "github_url": "https://github.com/django-cms/django-classy-tags"},
    {"dependency": "pytest-pylint", "github_url": "https://github.com/carsongee/pytest-pylint"},
    {"dependency": "cloudpickle", "github_url": "https://github.com/cloudpipe/cloudpickle"},
    {"dependency": "djangorestframework-csv", "github_url": "https://github.com/mjumbewu/django-rest-framework-csv"},
    {"dependency": "responses", "github_url": "https://github.com/getsentry/responses"},
    {"dependency": "pyminizip", "github_url": "https://github.com/smihica/pyminizip"},
    {"dependency": "google-cloud-storage", "github_url": "https://github.com/googleapis/python-storage"},
    {"dependency": "pyjwkest", "github_url": "No Project Links Tab"},
    {"dependency": "zope-event", "github_url": "https://github.com/zopefoundation/zope.event"},
    {"dependency": "pip-tools", "github_url": "https://github.com/jazzband/pip-tools"},
    {"dependency": "kubernetes", "github_url": "https://github.com/kubernetes-client/python"},
    {"dependency": "distlib", "github_url": "https://github.com/pypa/distlib"},
    {"dependency": "sphinx-mdinclude", "github_url": "https://github.com/omnilib/sphinx-mdinclude"},
    {"dependency": "pyinstaller-hooks-contrib", "github_url": "https://github.com/pyinstaller/pyinstaller-hooks-contrib"},
    {"dependency": "tutor", "github_url": "https://github.com/overhangio/tutor"},
    {"dependency": "smmap", "github_url": "https://github.com/gitpython-developers/smmap"},
    {"dependency": "django-pyfs", "github_url": "https://github.com/edx/django-pyfs"},
    {"dependency": "pillow-heif", "github_url": "https://github.com/bigcat88/pillow_heif"},
    {"dependency": "arrow", "github_url": "https://github.com/arrow-py/arrow"},
    {"dependency": "types-pyyaml", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "rcssmin", "github_url": "No Github Link"},
    {"dependency": "pytest-django", "github_url": "https://github.com/pytest-dev/pytest-django"},
    {"dependency": "social-auth-app-django", "github_url": "https://github.com/python-social-auth/social-app-django"},
    {"dependency": "bracex", "github_url": "https://github.com/facelessuser/bracex"},
    {"dependency": "simple-salesforce", "github_url": "https://github.com/simple-salesforce/simple-salesforce"},
    {"dependency": "datetime", "github_url": "https://github.com/zopefoundation/DateTime"},
    {"dependency": "scipy", "github_url": "https://github.com/scipy/scipy"},
    {"dependency": "django-treebeard", "github_url": "https://github.com/django-treebeard/django-treebeard/"},
    {"dependency": "graphql-core", "github_url": "https://github.com/graphql-python/graphql-core"},
    {"dependency": "needle", "github_url": "https://github.com/python-needle/needle"},
    {"dependency": "path", "github_url": "https://github.com/jaraco/path"},
    {"dependency": "cssutils", "github_url": "https://github.com/jaraco/cssutils"},
    {"dependency": "googleapis-common-protos", "github_url": "https://github.com/googleapis/python-api-common-protos"},
    {"dependency": "mypy", "github_url": "https://github.com/python/mypy"},
    {"dependency": "django-webtest", "github_url": "https://github.com/django-webtest/django-webtest"},
    {"dependency": "pip", "github_url": "https://github.com/pypa/pip"},
    {"dependency": "pyparsing", "github_url": "https://github.com/pyparsing/pyparsing/"},
    {"dependency": "docker", "github_url": "https://github.com/docker/docker-py"},
    {"dependency": "zstandard", "github_url": "https://github.com/indygreg/python-zstandard"},
    {"dependency": "hvac", "github_url": "https://github.com/hvac/hvac"},
    {"dependency": "pyopenssl", "github_url": "https://github.com/pyca/pyopenssl"},
    {"dependency": "pyuca", "github_url": "No Github Link"},
    {"dependency": "dj-database-url", "github_url": "https://github.com/jazzband/dj-database-url/"},
    {"dependency": "ruamel-yaml-base", "github_url": "No Github Link"},
    {"dependency": "acid-xblock", "github_url": "https://github.com/edx/acid-block"},
    {"dependency": "whitenoise", "github_url": "https://github.com/evansd/whitenoise"},
    {"dependency": "sphinxcontrib-youtube", "github_url": "https://github.com/sphinx-contrib/youtube"},
    {"dependency": "edx-when", "github_url": "https://github.com/openedx/edx-when"},
    {"dependency": "deprecated", "github_url": "https://github.com/tantale/deprecated"},
    {"dependency": "djangoql", "github_url": "https://github.com/ivelum/djangoql/"},
    {"dependency": "aiodns", "github_url": "https://github.com/saghul/aiodns"},
    {"dependency": "django-nested-admin", "github_url": "https://github.com/theatlantic/django-nested-admin"},
    {"dependency": "leather", "github_url": "No Github Link"},
    {"dependency": "urlobject", "github_url": "No Github Link"},
    {"dependency": "pynacl", "github_url": "https://github.com/pyca/pynacl/"},
    {"dependency": "watchdog", "github_url": "https://github.com/gorakhargosh/watchdog"},
    {"dependency": "awscli", "github_url": "https://github.com/aws/aws-cli"},
    {"dependency": "restructuredtext-lint", "github_url": "https://github.com/twolfson/restructuredtext-lint"},
    {"dependency": "dogstatsd-python", "github_url": "No Github Link"},
    {"dependency": "pycountry", "github_url": "https://github.com/flyingcircusio/pycountry"},
    {"dependency": "commonmark", "github_url": "https://github.com/rtfd/commonmark.py"},
    {"dependency": "ndg-httpsclient", "github_url": "https://github.com/cedadev/ndg_httpsclient/"},
    {"dependency": "anyascii", "github_url": "https://github.com/anyascii/anyascii"},
    {"dependency": "pytest-html", "github_url": "https://github.com/pytest-dev/pytest-html"},
    {"dependency": "edx-i18n-tools", "github_url": "https://github.com/openedx/i18n-tools"},
    {"dependency": "agate", "github_url": "https://github.com/wireservice/agate"},
    {"dependency": "social-auth-core", "github_url": "https://github.com/python-social-auth/social-core"},
    {"dependency": "pycryptodomex", "github_url": "https://github.com/Legrandin/pycryptodome/"},
    {"dependency": "sortedcontainers", "github_url": "No Github Link"},
    {"dependency": "twine", "github_url": "https://github.com/pypa/twine/"},
    {"dependency": "bleach", "github_url": "https://github.com/mozilla/bleach"},
    {"dependency": "click-plugins", "github_url": "https://github.com/click-contrib/click-plugins"},
    {"dependency": "pysocks", "github_url": "https://github.com/Anorov/PySocks"},
    {"dependency": "github3.py", "github_url": "https://github.com/sigmavirus24/github3.py"},
    {"dependency": "google-auth-httplib2", "github_url": "https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2"},
    {"dependency": "pact-python", "github_url": "No Github Link"},
    {"dependency": "interchange", "github_url": "https://github.com/py2neo-org/interchange"},
    {"dependency": "billiard", "github_url": "https://github.com/celery/billiard"},
    {"dependency": "ciso8601", "github_url": "https://github.com/closeio/ciso8601"},
    {"dependency": "voluptuous", "github_url": "https://github.com/alecthomas/voluptuous"},
    {"dependency": "joblib", "github_url": "https://github.com/joblib/joblib"},
    {"dependency": "binaryornot", "github_url": "https://github.com/audreyr/binaryornot"},
    {"dependency": "snowballstemmer", "github_url": "https://github.com/snowballstem/snowball"},
    {"dependency": "tinycss2", "github_url": "https://github.com/Kozea/tinycss2/"},
    {"dependency": "pgpy", "github_url": "https://github.com/SecurityInnovation/PGPy"},
    {"dependency": "jaraco-context", "github_url": "https://github.com/jaraco/jaraco.context"},
    {"dependency": "django-autocomplete-light", "github_url": "https://github.com/yourlabs/django-autocomplete-light"},
    {"dependency": "ordered-set", "github_url": "https://github.com/rspeer/ordered-set"},
    {"dependency": "openapi-schema-validator", "github_url": "https://github.com/python-openapi/openapi-schema-validator"},
    {"dependency": "pexpect", "github_url": "No Github Link"},
    {"dependency": "jsonschema-spec", "github_url": "https://github.com/p1c2u/jsonschema-spec"},
    {"dependency": "hologram", "github_url": "https://github.com/fishtown-analytics/hologram"},
    {"dependency": "texttable", "github_url": "https://github.com/foutaise/texttable/"},
    {"dependency": "exceptiongroup", "github_url": "https://github.com/agronholm/exceptiongroup"},
    {"dependency": "rq-dashboard", "github_url": "https://github.com/Parallels/rq-dashboard"},
    {"dependency": "django-sekizai", "github_url": "https://github.com/django-cms/django-sekizai"},
    {"dependency": "django-stubs", "github_url": "https://github.com/typeddjango/django-stubs"},
    {"dependency": "django-ratelimit", "github_url": "https://github.com/jsocol/django-ratelimit"},
    {"dependency": "edx-enterprise-data", "github_url": "https://github.com/openedx/edx-enterprise-data"},
    {"dependency": "cookiecutter", "github_url": "https://github.com/cookiecutter/cookiecutter"},
    {"dependency": "pygeoip", "github_url": "https://github.com/appliedsec/pygeoip"},
    {"dependency": "ipaddress", "github_url": "https://github.com/phihag/ipaddress"},
    {"dependency": "sympy", "github_url": "https://github.com/sympy/sympy"},
    {"dependency": "build", "github_url": "https://github.com/pypa/build"},
    {"dependency": "django-choices", "github_url": "https://github.com/bigjason/django-choices"},
    {"dependency": "blinker", "github_url": "https://github.com/pallets-eco/blinker/"},
    {"dependency": "atlassian-python-api", "github_url": "https://github.com/atlassian-api/atlassian-python-api"},
    {"dependency": "genanki", "github_url": "No Github Link"},
    {"dependency": "sphinxcontrib-serializinghtml", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-serializinghtml"},
    {"dependency": "pylint", "github_url": "https://github.com/pylint-dev/pylint"},
    {"dependency": "python-monkey-business", "github_url": "https://github.com/theatlantic/python-monkey-business"},
    {"dependency": "edx-name-affirmation", "github_url": "https://github.com/edx/edx-name-affirmation"},
    {"dependency": "pyhcl", "github_url": "https://github.com/virtuald/pyhcl"},
    {"dependency": "import-linter", "github_url": "https://github.com/seddonym/import-linter/"},
    {"dependency": "anyio", "github_url": "https://github.com/agronholm/anyio"},
    {"dependency": "pockets", "github_url": "No Github Link"},
    {"dependency": "pansi", "github_url": "https://github.com/technige/pansi"},
    {"dependency": "toml", "github_url": "https://github.com/uiri/toml"},
    {"dependency": "random2", "github_url": "No Github Link"},
    {"dependency": "ansible", "github_url": "https://github.com/ansible/ansible"},
    {"dependency": "et-xmlfile", "github_url": "No Github Link"},
    {"dependency": "tableauserverclient", "github_url": "https://github.com/tableau/server-client-python"},
    {"dependency": "xblock-utils", "github_url": "https://github.com/openedx/xblock-utils"},
    {"dependency": "execnet", "github_url": "No Github Link"},
    {"dependency": "wsgiref", "github_url": "No Github Link"},
    {"dependency": "colorama", "github_url": "https://github.com/tartley/colorama"},
    {"dependency": "nltk", "github_url": "https://github.com/nltk/nltk"},
    {"dependency": "backports.functools-lru-cache", "github_url": "https://github.com/jaraco/backports.functools_lru_cache"},
    {"dependency": "edx-toggles", "github_url": "https://github.com/openedx/edx-toggles"},
    {"dependency": "psycopg2", "github_url": "https://github.com/psycopg/psycopg2"},
    {"dependency": "argh", "github_url": "https://github.com/neithere/argh"},
    {"dependency": "zappa", "github_url": "https://github.com/zappa/Zappa"},
    {"dependency": "tox-travis", "github_url": "https://github.com/tox-dev/tox-travis"},
    {"dependency": "prefect", "github_url": "https://github.com/PrefectHQ/prefect"},
    {"dependency": "django-fernet-fields", "github_url": "https://github.com/orcasgit/django-fernet-fields/"},
    {"dependency": "codecov", "github_url": "https://github.com/codecov/codecov-python"},
    {"dependency": "setuptools", "github_url": "https://github.com/pypa/setuptools"},
    {"dependency": "face", "github_url": "https://github.com/mahmoud/face"},
    {"dependency": "requests", "github_url": "https://github.com/psf/requests"},
    {"dependency": "youtube-dl", "github_url": "https://github.com/ytdl-org/youtube-dl"},
    {"dependency": "webencodings", "github_url": "https://github.com/SimonSapin/python-webencodings"},
    {"dependency": "mysqlclient", "github_url": "https://github.com/PyMySQL/mysqlclient"},
    {"dependency": "jinja2-time", "github_url": "https://github.com/hackebrot/jinja2-time"},
    {"dependency": "strict-rfc3339", "github_url": "No Github Link"},
    {"dependency": "stevedore", "github_url": "No Github Link"},
    {"dependency": "cssselect", "github_url": "https://github.com/scrapy/cssselect"},
    {"dependency": "asyncio-extras", "github_url": "https://github.com/agronholm/asyncio_extras"},
    {"dependency": "idna", "github_url": "https://github.com/kjd/idna"},
    {"dependency": "placebo", "github_url": "https://github.com/garnaat/placebo"},
    {"dependency": "pyasn1-modules", "github_url": "https://github.com/pyasn1/pyasn1-modules"},
    {"dependency": "pytzdata", "github_url": "https://github.com/sdispater/pytzdata"},
    {"dependency": "purl", "github_url": "https://github.com/codeinthehole/purl"},
    {"dependency": "sphinxcontrib-qthelp", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-qthelp"},
    {"dependency": "itsdangerous", "github_url": "https://github.com/pallets/itsdangerous/"},
    {"dependency": "pycares", "github_url": "No Github Link"},
    {"dependency": "Sphinx", "github_url": "https://github.com/sphinx-doc/sphinx"},
    {"dependency": "unittest2", "github_url": "No Github Link"},
    {"dependency": "frozendict", "github_url": "https://github.com/Marco-Sulla/python-frozendict"},
    {"dependency": "marshmallow", "github_url": "https://github.com/marshmallow-code/marshmallow"},
    {"dependency": "jaraco-functools", "github_url": "https://github.com/jaraco/jaraco.functools"},
    {"dependency": "itypes", "github_url": "No Github Link"},
    {"dependency": "resolvelib", "github_url": "https://github.com/sarugaku/resolvelib"},
    {"dependency": "shellescape", "github_url": "https://github.com/chrissimpkins/shellescape"},
    {"dependency": "futures", "github_url": "https://github.com/agronholm/pythonfutures"},
    {"dependency": "ora2", "github_url": "No Github Link"},
    {"dependency": "dbt-core", "github_url": "https://github.com/dbt-labs/dbt-core"},
    {"dependency": "path.py", "github_url": "https://github.com/jaraco/path"},
    {"dependency": "jinja2-pluralize", "github_url": "https://github.com/audreyr/jinja2_pluralize"},
    {"dependency": "sphinxcontrib-mermaid", "github_url": "https://github.com/mgaitan/sphinxcontrib-mermaid"},
    {"dependency": "edx-organizations", "github_url": "https://github.com/openedx/edx-organizations"},
    {"dependency": "django-ipware", "github_url": "https://github.com/un33k/django-ipware"},
    {"dependency": "iso-639", "github_url": "https://github.com/noumar/iso639"},
    {"dependency": "xblock-google-drive", "github_url": "https://github.com/openedx/xblock-google-drive"},
    {"dependency": "boto3", "github_url": "https://github.com/boto/boto3"},
    {"dependency": "pygithub", "github_url": "https://github.com/pygithub/pygithub"},
    {"dependency": "django-taggit-autosuggest", "github_url": "No Github Link"},
    {"dependency": "more-itertools", "github_url": "https://github.com/more-itertools/more-itertools"},
    {"dependency": "rpds-py", "github_url": "https://github.com/crate-py/rpds"},
    {"dependency": "django-mysql", "github_url": "https://github.com/adamchainz/django-mysql"},
    {"dependency": "django-guardian", "github_url": "No Github Link"},
    {"dependency": "dbt-snowflake", "github_url": "https://github.com/dbt-labs/dbt-snowflake"},
    {"dependency": "ptyprocess", "github_url": "https://github.com/pexpect/ptyprocess"},
    {"dependency": "edx-milestones", "github_url": "https://github.com/openedx/edx-milestones"},
    {"dependency": "tomlkit", "github_url": "https://github.com/sdispater/tomlkit"},
    {"dependency": "cairocffi", "github_url": "https://github.com/Kozea/cairocffi/"},
    {"dependency": "azure-storage-nspkg", "github_url": "https://github.com/Azure/azure-storage-python"},
    {"dependency": "clickhouse-connect", "github_url": "https://github.com/ClickHouse/clickhouse-connect"},
    {"dependency": "cfn-flip", "github_url": "https://github.com/awslabs/aws-cfn-template-flip"},
    {"dependency": "sphinxcontrib-napoleon", "github_url": "No Github Link"},
    {"dependency": "xblock-sdk", "github_url": "No Project Links Tab"},
    {"dependency": "user-util", "github_url": "https://github.com/edx/user-util"},
    {"dependency": "google-api-python-client", "github_url": "https://github.com/googleapis/google-api-python-client/"},
    {"dependency": "edx-event-bus-kafka", "github_url": "https://github.com/openedx/event-bus-kafka"},
    {"dependency": "gitdb", "github_url": "https://github.com/gitpython-developers/gitdb"},
    {"dependency": "importlib-metadata", "github_url": "https://github.com/python/importlib_metadata"},
    {"dependency": "super-csv", "github_url": "https://github.com/openedx/super-csv"},
    {"dependency": "telepath", "github_url": "https://github.com/wagtail/telepath"},
    {"dependency": "drf-extensions", "github_url": "No Github Link"},
    {"dependency": "jinja2", "github_url": "https://github.com/pallets/jinja/"},
    {"dependency": "matplotlib", "github_url": "https://github.com/matplotlib/matplotlib"},
    {"dependency": "django-taggit", "github_url": "https://github.com/jazzband/django-taggit"},
    {"dependency": "keyring", "github_url": "https://github.com/jaraco/keyring"},
    {"dependency": "edx-analytics-data-api-client", "github_url": "https://github.com/openedx/edx-analytics-data-api-client"},
    {"dependency": "funcsigs", "github_url": "No Github Link"},
    {"dependency": "defusedxml", "github_url": "https://github.com/tiran/defusedxml"},
    {"dependency": "pyquery", "github_url": "https://github.com/gawel/pyquery"},
    {"dependency": "lazy-object-proxy", "github_url": "https://github.com/ionelmc/python-lazy-object-proxy"},
    {"dependency": "sphinx-copybutton", "github_url": "https://github.com/executablebooks/sphinx-copybutton"},
    {"dependency": "inflection", "github_url": "https://github.com/jpvanhal/inflection"},
    {"dependency": "graphviz", "github_url": "https://github.com/xflr6/graphviz"},
    {"dependency": "xblock-poll", "github_url": "No Project Links Tab"},
    {"dependency": "edx-rest-api-client", "github_url": "https://github.com/openedx/edx-rest-api-client"},
    {"dependency": "pandas", "github_url": "https://github.com/pandas-dev/pandas"},
    {"dependency": "bridgekeeper", "github_url": "https://github.com/excitedleigh/bridgekeeper"},
    {"dependency": "gevent", "github_url": "https://github.com/gevent/gevent/"},
    {"dependency": "contourpy", "github_url": "https://github.com/contourpy/contourpy"},
    {"dependency": "azure-storage-common", "github_url": "https://github.com/Azure/azure-storage-python"},
    {"dependency": "sphinxcontrib-htmlhelp", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-htmlhelp"},
    {"dependency": "sphinxcontrib-django", "github_url": "https://github.com/edoburu/sphinxcontrib-django"},
    {"dependency": "tempora", "github_url": "https://github.com/jaraco/tempora"},
    {"dependency": "vertica-python", "github_url": "https://github.com/vertica/vertica-python"},
    {"dependency": "picobox", "github_url": "https://github.com/ikalnytskyi/picobox"},
    {"dependency": "python-crontab", "github_url": "No Github Link"},
    {"dependency": "ecdsa", "github_url": "No Github Link"},
    {"dependency": "tabulate", "github_url": "https://github.com/astanin/python-tabulate"},
    {"dependency": "python-mimeparse", "github_url": "https://github.com/dbtsai/python-mimeparse"},
    {"dependency": "backports-csv", "github_url": "https://github.com/ryanhiebert/backports.csv"},
    {"dependency": "ijson", "github_url": "https://github.com/ICRAR/ijson"},
    {"dependency": "pymemcache", "github_url": "https://github.com/pinterest/pymemcache"},
    {"dependency": "srt", "github_url": "https://github.com/cdown/srt"},
    {"dependency": "edx-lint", "github_url": "https://github.com/openedx/edx-lint"},
    {"dependency": "polib", "github_url": "https://github.com/izimobil/polib/"},
    {"dependency": "premailer", "github_url": "No Github Link"},
    {"dependency": "pytest-forked", "github_url": "https://github.com/pytest-dev/pytest-forked"},
    {"dependency": "flask", "github_url": "https://github.com/pallets/flask/"},
    {"dependency": "filelock", "github_url": "https://github.com/tox-dev/py-filelock"},
    {"dependency": "stripe", "github_url": "https://github.com/stripe/stripe-python"},
    {"dependency": "elasticsearch", "github_url": "https://github.com/elastic/elasticsearch-py"},
    {"dependency": "qrcode", "github_url": "https://github.com/lincolnloop/python-qrcode"},
    {"dependency": "sniffio", "github_url": "https://github.com/python-trio/sniffio"},
    {"dependency": "yagocd", "github_url": "https://github.com/grundic/yagocd"},
    {"dependency": "types-pytz", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "scandir", "github_url": "https://github.com/benhoyt/scandir"},
    {"dependency": "extras", "github_url": "https://github.com/testing-cabal/extras"},
    {"dependency": "pytest-flakes", "github_url": "https://github.com/asmeurer/pytest-flakes"},
    {"dependency": "pytest-xdist", "github_url": "https://github.com/pytest-dev/pytest-xdist"},
    {"dependency": "django-webpack-loader", "github_url": "https://github.com/django-webpack/django-webpack-loader"},
    {"dependency": "geoip2", "github_url": "https://github.com/maxmind/GeoIP2-python"},
    {"dependency": "anki", "github_url": "No Project Links Tab"},
    {"dependency": "sphinxcontrib-contentui", "github_url": "https://github.com/ulrobix/sphinxcontrib-contentui"},
    {"dependency": "sarif-om", "github_url": "https://github.com/microsoft/sarif-python-om"},
    {"dependency": "pathable", "github_url": "https://github.com/p1c2u/pathable"},
    {"dependency": "webvtt-py", "github_url": "https://github.com/glut23/webvtt-py"},
    {"dependency": "pytest-json-report", "github_url": "https://github.com/numirias/pytest-json-report"},
    {"dependency": "semantic-version", "github_url": "https://github.com/rbarrois/python-semanticversion"},
    {"dependency": "jenkinsapi", "github_url": "No Project Links Tab"},
    {"dependency": "iniconfig", "github_url": "https://github.com/pytest-dev/iniconfig"},
    {"dependency": "algoliasearch", "github_url": "https://github.com/algolia/algoliasearch-client-python"},
    {"dependency": "bcrypt", "github_url": "https://github.com/pyca/bcrypt/"},
    {"dependency": "moreorless", "github_url": "https://github.com/thatch/moreorless/"},
    {"dependency": "wcmatch", "github_url": "https://github.com/facelessuser/wcmatch"},
    {"dependency": "ddt", "github_url": "https://github.com/datadriventests/ddt"},
    {"dependency": "pywatchman", "github_url": "https://github.com/facebook/watchman"},
    {"dependency": "done-xblock", "github_url": "https://github.com/openedx/DoneXBlock"},
    {"dependency": "django-waffle", "github_url": "No Github Link"},
    {"dependency": "djangorestframework-datatables", "github_url": "https://github.com/izimobil/django-rest-framework-datatables"},
    {"dependency": "hjson", "github_url": "No Github Link"},
    {"dependency": "rstcheck-core", "github_url": "https://github.com/rstcheck/rstcheck-core"},
    {"dependency": "codejail-includes", "github_url": "https://github.com/edx/codejail-includes"},
    {"dependency": "pytest-runner", "github_url": "https://github.com/pytest-dev/pytest-runner/"},
    {"dependency": "openedx-events", "github_url": "https://github.com/openedx/openedx-events"},
    {"dependency": "graphitesend", "github_url": "https://github.com/daniellawrence/graphitesend"},
    {"dependency": "jsonschema", "github_url": "https://github.com/python-jsonschema/jsonschema"},
    {"dependency": "accessible-pygments", "github_url": "https://github.com/Quansight-Labs/accessible-pygments"},
    {"dependency": "django-celery-beat", "github_url": "https://github.com/celery/django-celery-beat"},
    {"dependency": "bowler", "github_url": "https://github.com/facebookincubator/bowler"},
    {"dependency": "coreapi", "github_url": "https://github.com/core-api/python-client"},
    {"dependency": "edx-braze-client", "github_url": "https://github.com/edx/braze-client"},
    {"dependency": "multidict", "github_url": "https://github.com/aio-libs/multidict"},
    {"dependency": "annotated-types", "github_url": "No Project Links Tab"},
    {"dependency": "frozenlist", "github_url": "https://github.com/aio-libs/frozenlist"},
    {"dependency": "django-oscar", "github_url": "https://github.com/django-oscar/django-oscar"},
    {"dependency": "swagger2rst", "github_url": "https://github.com/Arello-Mobile/swagger2rst"},
    {"dependency": "pyinstrument", "github_url": "https://github.com/joerick/pyinstrument"},
    {"dependency": "networkx", "github_url": "https://github.com/networkx/networkx"},
    {"dependency": "xmlsec", "github_url": "https://github.com/mehcode/python-xmlsec"},
    {"dependency": "greenlet", "github_url": "https://github.com/python-greenlet/greenlet/"},
    {"dependency": "zeep", "github_url": "https://github.com/mvantellingen/python-zeep"},
    {"dependency": "sshpubkeys", "github_url": "https://github.com/ojarva/python-sshpubkeys"},
    {"dependency": "pytest-attrib", "github_url": "No Github Link"},
    {"dependency": "django-nine", "github_url": "https://github.com/barseghyanartur/django-nine"},
    {"dependency": "isodate", "github_url": "https://github.com/gweis/isodate/"},
    {"dependency": "django-debug-toolbar", "github_url": "https://github.com/jazzband/django-debug-toolbar"},
    {"dependency": "tox", "github_url": "https://github.com/tox-dev/tox"},
    {"dependency": "google-cloud-bigquery", "github_url": "https://github.com/googleapis/python-bigquery"},
    {"dependency": "edx-api-doc-tools", "github_url": "https://github.com/openedx/api-doc-tools"},
    {"dependency": "atomicwrites", "github_url": "https://github.com/untitaker/python-atomicwrites"},
    {"dependency": "django-elasticsearch-debug-toolbar", "github_url": "No Github Link"},
    {"dependency": "pytest", "github_url": "https://github.com/pytest-dev/pytest"},
    {"dependency": "enmerkar", "github_url": "https://github.com/Zegocover/enmerkar"},
    {"dependency": "logging-tree", "github_url": "https://github.com/brandon-rhodes/logging_tree"},
    {"dependency": "naked", "github_url": "https://github.com/chrissimpkins/naked"},
    {"dependency": "argcomplete", "github_url": "https://github.com/kislyuk/argcomplete"},
    {"dependency": "packaging", "github_url": "https://github.com/pypa/packaging"},
    {"dependency": "certifi", "github_url": "https://github.com/certifi/python-certifi"},
    {"dependency": "cloudflare", "github_url": "https://github.com/cloudflare/python-cloudflare"},
    {"dependency": "text-unidecode", "github_url": "https://github.com/kmike/text-unidecode/"},
    {"dependency": "logbook", "github_url": "https://github.com/getlogbook/logbook"},
    {"dependency": "jedi", "github_url": "https://github.com/davidhalter/jedi"},
    {"dependency": "cryptography", "github_url": "https://github.com/pyca/cryptography/"},
    {"dependency": "pydantic-core", "github_url": "https://github.com/pydantic/pydantic-core"},
    {"dependency": "sh", "github_url": "https://github.com/amoffat/sh"},
    {"dependency": "rstcheck", "github_url": "https://github.com/rstcheck/rstcheck"},
    {"dependency": "aiohttp", "github_url": "https://github.com/aio-libs/aiohttp"},
    {"dependency": "pytest-base-url", "github_url": "https://github.com/pytest-dev/pytest-base-url"},
    {"dependency": "edxval", "github_url": "No Github Link"},
    {"dependency": "onelogin", "github_url": "No Project Links Tab"},
    {"dependency": "mdurl", "github_url": "https://github.com/executablebooks/mdurl"},
    {"dependency": "transifex-client", "github_url": "No Github Link"},
    {"dependency": "pyasn1", "github_url": "https://github.com/pyasn1/pyasn1"},
    {"dependency": "pygments", "github_url": "https://github.com/pygments/pygments"},
    {"dependency": "rich", "github_url": "https://github.com/Textualize/rich"},
    {"dependency": "github3-py", "github_url": "https://github.com/sigmavirus24/github3.py"},
    {"dependency": "asgiref", "github_url": "https://github.com/django/asgiref/"},
    {"dependency": "google-crc32c", "github_url": "https://github.com/googleapis/python-crc32c"},
    {"dependency": "simplejson", "github_url": "https://github.com/simplejson/simplejson"},
    {"dependency": "configparser", "github_url": "https://github.com/jaraco/configparser/"},
    {"dependency": "tomli", "github_url": "https://github.com/hukkin/tomli"},
    {"dependency": "enmerkar-underscore", "github_url": "https://github.com/openedx/enmerkar-underscore"},
    {"dependency": "recommender-xblock", "github_url": "https://github.com/edx/RecommenderXBlock"},
    {"dependency": "python3-saml", "github_url": "https://github.com/SAML-Toolkits/python3-saml"},
    {"dependency": "tornado", "github_url": "https://github.com/tornadoweb/tornado"},
    {"dependency": "pep8", "github_url": "No Github Link"},
    {"dependency": "algoliasearch-django", "github_url": "https://github.com/algolia/algoliasearch-django"},
    {"dependency": "pyproject-api", "github_url": "https://github.com/tox-dev/pyproject-api"},
    {"dependency": "pyseeyou", "github_url": "https://github.com/rolepoint/pyseeyou"},
    {"dependency": "entrypoints", "github_url": "https://github.com/takluyver/entrypoints"},
    {"dependency": "django-parler", "github_url": "https://github.com/edoburu/django-parler"},
    {"dependency": "wrapt", "github_url": "https://github.com/GrahamDumpleton/wrapt"},
    {"dependency": "djangorestframework-stubs", "github_url": "https://github.com/typeddjango/djangorestframework-stubs"},
    {"dependency": "distro", "github_url": "https://github.com/python-distro/distro"},
    {"dependency": "opsgenie-sdk", "github_url": "https://github.com/opsgenie/opsgenie-python-sdk"},
    {"dependency": "selenium", "github_url": "No Github Link"},
    {"dependency": "marshmallow-oneofschema", "github_url": "https://github.com/marshmallow-code/marshmallow-oneofschema"},
    {"dependency": "drf-spectacular", "github_url": "https://github.com/tfranzel/drf-spectacular"},
    {"dependency": "scriv", "github_url": "https://github.com/sponsors/nedbat"},
    {"dependency": "oauth2client", "github_url": "No Github Link"},
    {"dependency": "macholib", "github_url": "https://github.com/ronaldoussoren/macholib"},
    {"dependency": "web-fragments", "github_url": "https://github.com/openedx/web-fragments"},
    {"dependency": "isoweek", "github_url": "No Github Link"},
    {"dependency": "edx-completion", "github_url": "https://github.com/openedx/completion"},
    {"dependency": "pyyaml", "github_url": "https://github.com/yaml/pyyaml"},
    {"dependency": "google-resumable-media", "github_url": "https://github.com/googleapis/google-resumable-media-python"},
    {"dependency": "paramiko", "github_url": "https://github.com/paramiko/paramiko"},
    {"dependency": "pycryptodome", "github_url": "https://github.com/Legrandin/pycryptodome/"},
    {"dependency": "django-stdimage", "github_url": "https://github.com/codingjoe/django-stdimage"},
    {"dependency": "sorl-thumbnail", "github_url": "https://github.com/jazzband/sorl-thumbnail"},
    {"dependency": "sphinx-design", "github_url": "https://github.com/executablebooks/sphinx-design"},
    {"dependency": "pytest-catchlog", "github_url": "https://github.com/eisensheng/pytest-catchlog"},
    {"dependency": "yarl", "github_url": "https://github.com/aio-libs/yarl/"},
    {"dependency": "django-mptt", "github_url": "https://github.com/django-mptt/django-mptt/"},
    {"dependency": "google-auth-oauthlib", "github_url": "https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib"},
    {"dependency": "mechanize", "github_url": "https://github.com/python-mechanize/mechanize"},
    {"dependency": "openapi-spec-validator", "github_url": "https://github.com/python-openapi/openapi-spec-validator"},
    {"dependency": "openedx-django-require", "github_url": "https://github.com/etianen/django-require"},
    {"dependency": "charset-normalizer", "github_url": "https://github.com/Ousret/charset_normalizer"},
    {"dependency": "sphinxcontrib-jsmath", "github_url": "No Github Link"},
    {"dependency": "markdown-it-py", "github_url": "https://github.com/executablebooks/markdown-it-py"},
    {"dependency": "aiosignal", "github_url": "https://github.com/aio-libs/aiosignal"},
    {"dependency": "azure-nspkg", "github_url": "https://github.com/Azure/azure-sdk-for-python"},
    {"dependency": "toolz", "github_url": "https://github.com/pytoolz/toolz/"},
    {"dependency": "phonenumbers", "github_url": "https://github.com/daviddrysdale/python-phonenumbers"},
    {"dependency": "lockfile", "github_url": "No Github Link"},
    {"dependency": "openedx-mongodbproxy", "github_url": "https://github.com/arngarden/MongoDBProxy"},
    {"dependency": "caniusepython3", "github_url": "https://github.com/brettcannon/caniusepython3"},
    {"dependency": "drf-flex-fields", "github_url": "https://github.com/rsinger86/drf-flex-fields"},
    {"dependency": "google-cloud-core", "github_url": "https://github.com/googleapis/python-cloud-core"},
    {"dependency": "pytest-cache", "github_url": "No Github Link"},
    {"dependency": "platformdirs", "github_url": "https://github.com/platformdirs/platformdirs"},
    {"dependency": "pycrypto", "github_url": "No Github Link"},
    {"dependency": "babel", "github_url": "https://github.com/python-babel/babel"},
    {"dependency": "aws-sam-translator", "github_url": "https://github.com/awslabs/serverless-application-model"},
    {"dependency": "pytest-mock", "github_url": "https://github.com/pytest-dev/pytest-mock/"},
    {"dependency": "django-sortedm2m", "github_url": "https://github.com/jazzband/django-sortedm2m"},
    {"dependency": "distributed", "github_url": "https://github.com/dask/distributed"},
    {"dependency": "pathspec", "github_url": "https://github.com/cpburnz/python-pathspec"},
    {"dependency": "sphinx-intl", "github_url": "https://github.com/sphinx-doc/sphinx-intl"},
    {"dependency": "edx-auth-backends", "github_url": "https://github.com/openedx/auth-backends"},
    {"dependency": "mpmath", "github_url": "https://github.com/fredrik-johansson/mpmath"},
    {"dependency": "testfixtures", "github_url": "https://github.com/Simplistix/testfixtures"},
    {"dependency": "types-requests", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "httpx", "github_url": "https://github.com/encode/httpx"},
    {"dependency": "pytest-variables", "github_url": "https://github.com/pytest-dev/pytest-variables"},
    {"dependency": "paver", "github_url": "https://github.com/paver/paver"},
    {"dependency": "coveralls", "github_url": "No Github Link"},
    {"dependency": "pathlib2", "github_url": "https://github.com/jazzband/pathlib2"},
    {"dependency": "jsonschema-specifications", "github_url": "https://github.com/sponsors/Julian"},
    {"dependency": "django-oauth-toolkit", "github_url": "https://github.com/jazzband/django-oauth-toolkit"},
    {"dependency": "sqlalchemy", "github_url": "https://github.com/sqlalchemy/sqlalchemy/"},
    {"dependency": "django-multi-email-field", "github_url": "No Project Links Tab"},
    {"dependency": "django-extensions", "github_url": "https://github.com/django-extensions/django-extensions"},
    {"dependency": "openedx-atlas", "github_url": "https://github.com/openedx/openedx-atlas"},
    {"dependency": "pymysql", "github_url": "https://github.com/PyMySQL/PyMySQL"},
    {"dependency": "mistune", "github_url": "https://github.com/lepture/mistune"},
    {"dependency": "wcwidth", "github_url": "https://github.com/jquast/wcwidth"},
    {"dependency": "help-tokens", "github_url": "https://github.com/openedx/help-tokens"},
    {"dependency": "testtools", "github_url": "https://github.com/testing-cabal/testtools"},
    {"dependency": "async-timeout", "github_url": "https://github.com/aio-libs/async-timeout"},
    {"dependency": "mypy-extensions", "github_url": "https://github.com/python/mypy_extensions"},
    {"dependency": "readme-renderer", "github_url": "https://github.com/pypa/readme_renderer"},
    {"dependency": "drf-nested-routers", "github_url": "https://github.com/alanjds/drf-nested-routers"},
    {"dependency": "types-cachetools", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "user-agents", "github_url": "https://github.com/selwin/python-user-agents"},
    {"dependency": "glob2", "github_url": "No Github Link"},
    {"dependency": "singledispatch", "github_url": "https://github.com/jaraco/singledispatch"},
    {"dependency": "backports-zoneinfo", "github_url": "https://github.com/pganssle/zoneinfo"},
    {"dependency": "markey", "github_url": "No Github Link"},
    {"dependency": "py", "github_url": "No Github Link"},
    {"dependency": "edx-bulk-grades", "github_url": "https://github.com/openedx/edx-bulk-grades"},
    {"dependency": "easydict", "github_url": "https://github.com/makinacorpus/easydict"},
    {"dependency": "bumpversion", "github_url": "https://github.com/peritus/bumpversion"},
    {"dependency": "async-generator", "github_url": "https://github.com/python-trio/async_generator"},
    {"dependency": "webtest", "github_url": "No Github Link"},
    {"dependency": "pytest-randomly", "github_url": "https://github.com/pytest-dev/pytest-randomly"},
    {"dependency": "openedx-filters", "github_url": "https://github.com/openedx/openedx-filters"},
    {"dependency": "ruamel-yaml", "github_url": "No Github Link"},
    {"dependency": "newrelic", "github_url": "https://github.com/newrelic/newrelic-python-agent"},
    {"dependency": "regex", "github_url": "https://github.com/mrabarnett/mrab-regex"},
    {"dependency": "cachetools", "github_url": "https://github.com/tkem/cachetools/"},
    {"dependency": "django-permissionedforms", "github_url": "https://github.com/wagtail/django-permissionedforms"},
    {"dependency": "bok-choy", "github_url": "No Github Link"},
    {"dependency": "importlib-resources", "github_url": "https://github.com/python/importlib_resources"},
    {"dependency": "mccabe", "github_url": "https://github.com/pycqa/mccabe"},
    {"dependency": "django-widget-tweaks", "github_url": "https://github.com/jazzband/django-widget-tweaks"},
    {"dependency": "laboratory", "github_url": "https://github.com/joealcorn/laboratory"},
    {"dependency": "wsgi-request-logger", "github_url": "https://github.com/pklaus/wsgi-request-logger"},
    {"dependency": "monotonic", "github_url": "https://github.com/atdt/monotonic"},
    {"dependency": "flask-sslify", "github_url": "https://github.com/kennethreitz/flask-sslify"},
    {"dependency": "urwid-readline", "github_url": "https://github.com/rr-/urwid_readline"},
    {"dependency": "sphinx", "github_url": "https://github.com/sphinx-doc/sphinx"},
    {"dependency": "wagtail", "github_url": "https://github.com/wagtail/wagtail"},
    {"dependency": "edx-event-bus-redis", "github_url": "https://github.com/openedx/event-bus-redis"},
    {"dependency": "sphinxcontrib-openapi", "github_url": "https://github.com/sphinx-contrib/openapi"},
    {"dependency": "html5lib", "github_url": "https://github.com/html5lib/html5lib-python"},
    {"dependency": "wsproto", "github_url": "https://github.com/python-hyper/wsproto/"},
    {"dependency": "pytest-logging", "github_url": "https://github.com/saltstack/pytest-logging"},
    {"dependency": "mysql-connector-python", "github_url": "No Github Link"},
    {"dependency": "backports-abc", "github_url": "https://github.com/cython/backports_abc"},
    {"dependency": "edx-proctoring", "github_url": "https://github.com/openedx/edx-proctoring"},
    {"dependency": "pylint-pytest", "github_url": "https://github.com/pylint-dev/pylint-pytest"},
    {"dependency": "tzdata", "github_url": "https://github.com/python/tzdata"},
    {"dependency": "black", "github_url": "https://github.com/psf/black"},
    {"dependency": "confluent-kafka", "github_url": "https://github.com/confluentinc/confluent-kafka-python"},
    {"dependency": "msgpack", "github_url": "https://github.com/msgpack/msgpack-python/"},
    {"dependency": "jwcrypto", "github_url": "https://github.com/latchset/jwcrypto"},
    {"dependency": "docker-compose", "github_url": "https://github.com/docker/compose"},
    {"dependency": "proto-plus", "github_url": "https://github.com/googleapis/proto-plus-python.git"},
    {"dependency": "httplib2", "github_url": "https://github.com/httplib2/httplib2"},
    {"dependency": "fs", "github_url": "https://github.com/PyFilesystem/pyfilesystem2"},
    {"dependency": "outcome", "github_url": "https://github.com/python-trio/outcome"},
    {"dependency": "python-termstyle", "github_url": "No Github Link"},
    {"dependency": "openai", "github_url": "https://github.com/openai/openai-python"},
    {"dependency": "openedx-django-wiki", "github_url": "https://github.com/openedx/django-wiki"},
    {"dependency": "kiwisolver", "github_url": "https://github.com/nucleic/kiwi"},
    {"dependency": "django-clearcache", "github_url": "https://github.com/timonweb/django-clearcache"},
    {"dependency": "jsonpointer", "github_url": "https://github.com/stefankoegl/python-json-pointer"},
    {"dependency": "edx-opaque-keys", "github_url": "https://github.com/openedx/opaque-keys"},
    {"dependency": "pudb", "github_url": "https://github.com/inducer/pudb"},
    {"dependency": "pynliner", "github_url": "No Project Links Tab"},
    {"dependency": "traceback2", "github_url": "https://github.com/testing-cabal/traceback2"},
    {"dependency": "flaky", "github_url": "https://github.com/box/flaky"},
    {"dependency": "sentry-sdk", "github_url": "https://github.com/getsentry/sentry-python"},
    {"dependency": "djangorestframework", "github_url": "https://github.com/encode/django-rest-framework"},
    {"dependency": "ruamel-yaml-clib", "github_url": "No Github Link"},
    {"dependency": "django-solo", "github_url": "https://github.com/lazybird/django-solo/"},
    {"dependency": "pep517", "github_url": "https://github.com/pypa/pep517"},
    {"dependency": "azure-common", "github_url": "https://github.com/Azure/azure-sdk-for-python"},
    {"dependency": "zc-lockfile", "github_url": "https://github.com/zopefoundation/zc.lockfile"},
    {"dependency": "mongoengine", "github_url": "No Github Link"},
    {"dependency": "piexif", "github_url": "https://github.com/hMatoba/Piexif"},
    {"dependency": "troposphere", "github_url": "https://github.com/cloudtools/troposphere"},
    {"dependency": "django-ses", "github_url": "https://github.com/django-ses/django-ses"},
    {"dependency": "xmltodict", "github_url": "https://github.com/martinblech/xmltodict"},
    {"dependency": "slacker", "github_url": "No Github Link"},
    {"dependency": "pkginfo", "github_url": "No Github Link"},
    {"dependency": "rjsmin", "github_url": "No Github Link"},
    {"dependency": "backports-functools-lru-cache", "github_url": "https://github.com/jaraco/backports.functools_lru_cache"},
    {"dependency": "optimizely-sdk", "github_url": "https://github.com/optimizely/python-sdk"},
    {"dependency": "peewee", "github_url": "https://github.com/coleifer/peewee/"},
    {"dependency": "python-coveralls", "github_url": "No Github Link"},
    {"dependency": "django-fsm", "github_url": "No Github Link"},
    {"dependency": "python-box", "github_url": "https://github.com/cdgriffith/Box"},
    {"dependency": "statistics", "github_url": "No Project Links Tab"},
    {"dependency": "soupsieve", "github_url": "https://github.com/facelessuser/soupsieve"},
    {"dependency": "orjson", "github_url": "https://github.com/ijl/orjson"},
    {"dependency": "typing-extensions", "github_url": "https://github.com/python/typing_extensions"},
    {"dependency": "luigi", "github_url": "https://github.com/spotify/luigi"},
    {"dependency": "python-lsp-jsonrpc", "github_url": "https://github.com/python-lsp/python-lsp-jsonrpc"},
    {"dependency": "drf-yasg", "github_url": "https://github.com/axnsan12/drf-yasg"},
    {"dependency": "referencing", "github_url": "https://github.com/sponsors/Julian"},
    {"dependency": "inflect", "github_url": "https://github.com/jaraco/inflect"},
    {"dependency": "pytimeparse", "github_url": "https://github.com/wroberts/pytimeparse"},
    {"dependency": "pytest-pycodestyle", "github_url": "https://github.com/henry0312/pytest-pycodestyle"},
    {"dependency": "fonttools", "github_url": "No Github Link"},
    {"dependency": "django-extra-views", "github_url": "https://github.com/AndrewIngram/django-extra-views"},
    {"dependency": "websocket-client", "github_url": "https://github.com/websocket-client/websocket-client/"},
    {"dependency": "urwid", "github_url": "https://github.com/urwid/urwid"},
    {"dependency": "jschema-to-python", "github_url": "https://github.com/microsoft/jschema-to-python"},
    {"dependency": "parsedatetime", "github_url": "https://github.com/bear/parsedatetime"},
    {"dependency": "slumber", "github_url": "No Github Link"},
    {"dependency": "pytest-metadata", "github_url": "https://github.com/pytest-dev/pytest-metadata"},
    {"dependency": "python-gnupg", "github_url": "https://github.com/vsajip/python-gnupg"},
    {"dependency": "edx-enterprise-subsidy-client", "github_url": "https://github.com/openedx/edx-enterprise-subsidy-client"},
    {"dependency": "tincan", "github_url": "No Github Link"},
    {"dependency": "zipp", "github_url": "https://github.com/jaraco/zipp"},
    {"dependency": "lazy", "github_url": "https://github.com/stefanholek/lazy"},
    {"dependency": "python-stdnum", "github_url": "https://github.com/arthurdejong/python-stdnum/"},
    {"dependency": "cffi", "github_url": "https://github.com/python-cffi/cffi"},
    {"dependency": "uvicorn", "github_url": "https://github.com/sponsors/encode"},
    {"dependency": "types-setuptools", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "prompt-toolkit", "github_url": "https://github.com/prompt-toolkit/python-prompt-toolkit"},
    {"dependency": "requests-mock", "github_url": "https://github.com/jamielennox/requests-mock"},
    {"dependency": "pydocstyle", "github_url": "https://github.com/PyCQA/pydocstyle"},
    {"dependency": "fastavro", "github_url": "https://github.com/fastavro/fastavro"},
    {"dependency": "types-urllib3", "github_url": "https://github.com/python/typeshed"},
    {"dependency": "django-dry-rest-permissions", "github_url": "https://github.com/FJNR-inc/dry-rest-permissions"},
    {"dependency": "python-dotenv", "github_url": "https://github.com/theskumar/python-dotenv"},
    {"dependency": "pyproject-hooks", "github_url": "https://github.com/pypa/pyproject-hooks"},
    {"dependency": "rfc3986", "github_url": "No Github Link"},
    {"dependency": "amqp", "github_url": "No Github Link"},
    {"dependency": "typer", "github_url": "https://github.com/tiangolo/typer"},
    {"dependency": "future", "github_url": "No Github Link"},
    {"dependency": "typing", "github_url": "https://github.com/python/typing"},
    {"dependency": "django-rest-swagger", "github_url": "https://github.com/marcgibbons/django-rest-swagger"},
    {"dependency": "paypalrestsdk", "github_url": "https://github.com/paypal/PayPal-Python-SDK"},
    {"dependency": "beautifulsoup4", "github_url": "No Github Link"},
    {"dependency": "pendulum", "github_url": "https://github.com/sdispater/pendulum"},
    {"dependency": "moto", "github_url": "https://github.com/getmoto/moto"},
    {"dependency": "jsonpickle", "github_url": "https://github.com/jsonpickle/jsonpickle"},
    {"dependency": "sphinx-reredirects", "github_url": "No Github Link"},
    {"dependency": "yarn-api-client", "github_url": "https://github.com/CODAIT/hadoop-yarn-api-python-client"},
    {"dependency": "inapppy", "github_url": "https://github.com/dotpot/InAppPy"},
    {"dependency": "grpcio-status", "github_url": "No Github Link"},
    {"dependency": "google-api-core", "github_url": "https://github.com/googleapis/python-api-core"},
    {"dependency": "trio-websocket", "github_url": "https://github.com/python-trio/trio-websocket"},
    {"dependency": "dbt-extractor", "github_url": "https://github.com/dbt-labs/dbt-parser-generator/"},
    {"dependency": "icalendar", "github_url": "https://github.com/collective/icalendar"},
    {"dependency": "grpcio", "github_url": "https://github.com/grpc/grpc"},
    {"dependency": "zappa-manage", "github_url": "https://github.com/edx/zappa-manage"},
    {"dependency": "pytest-selenium", "github_url": "https://github.com/pytest-dev/pytest-selenium"},
    {"dependency": "rules", "github_url": "No Github Link"},
    {"dependency": "grpc-google-iam-v1", "github_url": "https://github.com/googleapis/python-grpc-google-iam-v1"},
    {"dependency": "django-log-request-id", "github_url": "https://github.com/dabapps/django-log-request-id/"},
    {"dependency": "fastapi", "github_url": "https://github.com/tiangolo/fastapi"},
    {"dependency": "asym-crypto-yaml", "github_url": "No Project Links Tab"},
    {"dependency": "jmespath", "github_url": "https://github.com/jmespath/jmespath.py"},
    {"dependency": "pytest-aiohttp", "github_url": "https://github.com/aio-libs/pytest-aiohttp"},
    {"dependency": "parso", "github_url": "https://github.com/davidhalter/parso"},
    {"dependency": "parse", "github_url": "https://github.com/r1chardj0n3s/parse"},
    {"dependency": "django-tables2", "github_url": "https://github.com/jieter/django-tables2/"},
    {"dependency": "jira", "github_url": "https://github.com/pycontribs/jira"},
    {"dependency": "pycparser", "github_url": "https://github.com/eliben/pycparser"},
    {"dependency": "webob", "github_url": "No Github Link"},
    {"dependency": "python-memcached", "github_url": "https://github.com/linsomniac/python-memcached"},
    {"dependency": "django-dynamic-fixture", "github_url": "https://github.com/paulocheque/django-dynamic-fixture"},
    {"dependency": "django-admin-sortable2", "github_url": "https://github.com/jrief/django-admin-sortable2"},
    {"dependency": "pep257", "github_url": "https://github.com/GreenSteam/pep257/"},
    {"dependency": "pyresttest", "github_url": "https://github.com/svanoort/pyresttest"},
    {"dependency": "edx-sphinx-theme", "github_url": "https://github.com/openedx/edx-sphinx-theme"},
    {"dependency": "django-libsass", "github_url": "https://github.com/torchbox/django-libsass"},
    {"dependency": "numpy", "github_url": "https://github.com/numpy/numpy"},
    {"dependency": "slackclient", "github_url": "https://github.com/slackapi/python-slack-sdk"},
    {"dependency": "edx-django-utils", "github_url": "https://github.com/openedx/edx-django-utils"},
    {"dependency": "walrus", "github_url": "No Github Link"},
    {"dependency": "pytest-split", "github_url": "https://github.com/jerry-git/pytest-split"},
    {"dependency": "pkgutil-resolve-name", "github_url": "https://github.com/graingert/pkgutil-resolve-name"},
    {"dependency": "crowdsourcehinter-xblock", "github_url": "https://github.com/edx/crowdsourcehinter"},
    {"dependency": "sphinxcontrib-jquery", "github_url": "https://github.com/sphinx-contrib/jquery/"},
    {"dependency": "argparse", "github_url": "https://github.com/ThomasWaldmann/argparse/"},
    {"dependency": "sphinxcontrib-applehelp", "github_url": "https://github.com/sphinx-doc/sphinxcontrib-applehelp"},
    {"dependency": "code-annotations", "github_url": "https://github.com/openedx/code-annotations"},
    {"dependency": "shellingham", "github_url": "https://github.com/sarugaku/shellingham"},
    {"dependency": "cachecontrol", "github_url": "https://github.com/psf/cachecontrol"},
    {"dependency": "fs-s3fs", "github_url": "https://github.com/PyFilesystem/s3fs"},
    {"dependency": "google-compute-engine", "github_url": "https://github.com/GoogleCloudPlatform/compute-image-packages"},
    {"dependency": "transifex-python", "github_url": "https://github.com/transifex/transifex-python"},
    {"dependency": "django-crispy-forms", "github_url": "https://github.com/django-crispy-forms/django-crispy-forms"},
    {"dependency": "hypothesis-pytest", "github_url": "https://github.com/DRMacIver/hypothesis"},
    {"dependency": "sphinxext-rediraffe", "github_url": "https://github.com/wpilibsuite/sphinxext-rediraffe"},
    {"dependency": "ujson", "github_url": "https://github.com/ultrajson/ultrajson"},
    {"dependency": "pytest-cookies", "github_url": "https://github.com/hackebrot/pytest-cookies"},
    {"dependency": "lxml", "github_url": "https://github.com/lxml/lxml"},
    {"dependency": "edx-rbac", "github_url": "https://github.com/openedx/edx-rbac"},
    {"dependency": "django-localflavor", "github_url": "https://github.com/django/django-localflavor"},
    {"dependency": "isort", "github_url": "https://github.com/pycqa/isort"},
    {"dependency": "click-option-group", "github_url": "https://github.com/click-contrib/click-option-group"},
    {"dependency": "durationpy", "github_url": "https://github.com/icholy/durationpy"},
    {"dependency": "django-celery-results", "github_url": "https://github.com/celery/django-celery-results"},
    {"dependency": "django-pipeline", "github_url": "https://github.com/jazzband/django-pipeline"},
    {"dependency": "crypto", "github_url": "https://github.com/chrissimpkins/crypto"},
    {"dependency": "pyinstaller", "github_url": "https://github.com/pyinstaller/pyinstaller"},
]
